apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvclaim
  labels:
    app: mongodb
  namespace: flask-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi